import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const lexend = Lexend({
    variable: "--font-lexend",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    ...[geistSans, geistMono, lexend].map((f) => f.variable),
                    "antialiased",
                    "flex flex-col min-h-screen",
                )}
            >
                <header className="h-48 mb-2 mx-auto max-w-4xl w-full select-none">
                    <div className="h-full flex flex-row items-center">
                        <div>
                            <p className="text-4xl font-bold">
                                <Link href="/" tabIndex={-1}>
                                    CSP Solvers
                                </Link>
                            </p>
                        </div>
                        <div></div>
                    </div>
                </header>
                <main className="grow mb-8 mx-auto max-w-4xl w-full">{children}</main>
                <footer className="justify-self-end mx-auto max-w-4xl w-full text-[#cf3d3d] select-none">
                    <div className="py-8 text-4xl font-bold">
                        <p>A collection of CSP solvers.</p>
                    </div>
                    <div></div>
                </footer>
            </body>
        </html>
    );
}
